version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: base

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: base
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
